### ISSUE TITLE
collectstatic fails to find images (using whitenoise) 

### ISSUE THREAD

**Issue by werdnav** [randlet/django-listable#8]
collectstatic fails to find "listable/images/sort_both.png" as the css is pointing to an incorrect location. The image is actually stored at "listable/img/sort_both.png''.

To replicate this issue: 
```
git clone https://github.com/werdnav/python-getting-started
cd python-getting-started
virtualenv env
source env/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
python manage.py migrate
python manage.py collectstatic
```
collectstatic returns: 
```
Post-processing 'listable/css/jquery.dataTables.css' failed!

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/andrew/Documents/repo/python-getting-started/env/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 128, in collect
    raise processed
whitenoise.django.MissingFileError: The file 'listable/images/sort_both.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x7f7fa6f48ed0>.

The CSS file 'listable/css/jquery.dataTables.css' references a file which could not be found:
  listable/images/sort_both.png

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```
Looking at jquery.dataTables.css, the css appear to point to directory "images": 
```
.sorting { background: url('../images/sort_both.png') no-repeat center right; }
.sorting_asc { background: url('../images/sort_asc.png') no-repeat center right; }
.sorting_desc { background: url('../images/sort_desc.png') no-repeat center right; }

.sorting_asc_disabled { background: url('../images/sort_asc_disabled.png') no-repeat center right; }
.sorting_desc_disabled { background: url('../images/sort_desc_disabled.png') no-repeat center right; }
```
However, the "images" directory is actually named "img":

```
static/
- css
- img/
- - sort_both.png
- js
```

Note: this is tested using Linux Mint 17.2, Python 2.7.

**Comment by randlet** [comment]
Should be fixed by 0489dac.  Thanks for reporting!
